### ISSUE TITLE
nested behavior

### ISSUE THREAD

**Issue by ljcrapo** [mateodelnorte/meta-project#3]
when calling `meta project add ...` if the project I'm adding is a meta repo, it should also behave the same as if I'd called `meta git clone ...`.

**Comment by mateodelnorte** [comment]
meta-project doesn't assume your remote exists yet. it just adds the info. it's up to you to do a `meta git pull origin master` or whatever command you want to do, to pull in your remote. some people will do a `meta project add X git://X` before the remote exists, in which case it doesn't make sense to force a pull – which would be required to do a `meta git update` after detecting a .meta file.

**Comment by ljcrapo** [comment]
makes sense. I didn't consider that use case.
