### ISSUE TITLE
Projects cannot be outside the meta repo

### ISSUE THREAD

**Issue by glaucoleme** [mateodelnorte/meta-project#30]
## 🤓 Question

Are there any special reason for not importing repositories outside the actual repository?

meta-project-import:32-37
```
const metaPath = getMetaFile.getFileLocation();
const dest = path.relative(path.dirname(metaPath), path.resolve(destArg));
if (dest[0] === '.') {
    console.error(`💥 Projects cannot be outside the meta repo: ${cyan(dest)}`); // prettier-ignore
    process.exit(1);
}
```

**Comment by mateodelnorte** [comment]
There area number of reasons. What if the path to your project is `../../../../../../myproject`: 'git://..."`, then someone `meta git clone`s that directly under `/`?
