### ISSUE TITLE
"meta project import" should support custom branches

### ISSUE THREAD

**Issue by aleclarson** [mateodelnorte/meta-project#36]
## 🚀 Feature Proposal

The `projects` object in `.meta` should support custom git branches.

## Motivation

The `master` branch isn't always appropriate.

## Example

```sh
meta project import foo https://github.com/aleclarson/foo.git -b not-master
```

The `.meta` config could look like this:

```json
{
  "projects": {
    "foo": {
      "url": "https://github.com/aleclarson/foo.git",
      "branch": "not-master"
    }
  }
}
```

**Comment by mateodelnorte** [comment]
I don't get it. This is default git behavior that doesn't need meta data,
no? git clone will always get you the default branch, and after that it
doesn't really matter.

Am I missing some other workflow?

**Comment by aleclarson** [comment]
It's a matter of using Meta to create a reproducible setup of multiple repositories that are used together.

**Comment by mateodelnorte** [comment]
Right, but what does the branch specification get you? By default, you're
going to get the default branch from the remote. And once you've cloned,
all bets are off anyway because now you're working and changing branches at
will.

**Comment by aleclarson** [comment]
> By default, you're going to get the default branch from the remote.

The `git clone` command has a `-b` flag to avoid exactly that.

**Comment by mateodelnorte** [comment]
Sure, but why avoid that?

**Comment by mateodelnorte** [comment]
I feel like this is asking for two sources of truth.

**Comment by aleclarson** [comment]
I always considered the `projects` object in `.meta` to be describing the initial "state", not the current state. Is that not the case?

**Comment by mateodelnorte** [comment]
It's both, since it only lists remotes. The default branch is already
stored somewhere else, is my point. What is correct when GitHub says QA is
default and .meta says staging?

**Comment by aleclarson** [comment]
`.meta` would override the default branch. If I manually change `projects`, when would Meta respect that manual change? If never, then I would say `projects` represents the initial state only.
