### ISSUE TITLE
missing remove

### ISSUE THREAD

**Issue by ljcrapo** [mateodelnorte/meta-project#4]
This plugin appears incomplete, I expected a `meta project remove <file-path>` to exist, but it either doesn't or it is not documented.

**Comment by mateodelnorte** [comment]
Want to make a PR for this? Thx

**Comment by mateodelnorte** [comment]
👍

**Comment by DarioSarra** [comment]
Any updates or instructions on how to remove a child project? This seems to be the only relevant page I can find from a google search.
Thanks
