### ISSUE TITLE
create uses git remote remove origin but if no origin exists

### ISSUE THREAD

**Issue by deviprsd** [mateodelnorte/meta-project#54]
## 🐛 Bug Report

git remote remove origin throws fatal error if origin doesn't exist and meta create uses it to initialized the child repositories and hence the child repo don't have a remote added to them. The current fix is removing the folders and running meta git update so that everything clones properly

**Comment by cyrille-gachot** [comment]
As far as I know, this bug is still present. Any chance it gets fixed please ?
